GET http://localhost:3000/products.json

###

GET http://localhost:3000/products/84

###
POST http://localhost:3000/products
Content-Type: application/json

{
  "input_name": "Sam Adams",
  "input_price": 5,
  "input_description": "A tasty Boston beer"
}

###
PATCH http://localhost:3000/products/17.json
Content-Type: application/json

{
  "input_name": "Budweisser",
  "input_price": 3,
  "input_description": "Cheap tailgating beer"
}