GET http://localhost:3000/products.json

###

GET http://localhost:3000/products/84

###
POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "Buddy Light",
  "price": -5,
  "description": "Simple Beer"
}

###
PATCH http://localhost:3000/products/17.json
Content-Type: application/json

{
  "name": "Buddy Light",
  "price": 3,
  "description": "Cheap tailgating beer"
}

###
DELETE http://localhost:3000/products/5.json