@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2MzUyOTExNDJ9.Cft9xNlTkIbh1Gcof9sTa6ahw5DlPOEdNLwhIsQ0N9o

@bob = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2MzU3ODQxNDh9.vEABJQU8I3fmH277tfO3S-rztgYc_M5lljy3AQEoMVU

@joe = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2MzU3ODM5OTd9.ulykyrVgNbTzCbgPPiASTal2yoJX02Y7YXFH4-ee4EM

##THESE ARE ALL PRODUCT ROUTES
#Index action for all products
GET http://localhost:3000/products.json
Authorization: Bearer {{joe}}

###Show action for just one product
GET http://localhost:3000/products/1

###Create action for new product
POST http://localhost:3000/products
Authorization: Bearer {{joe}}
Content-Type: application/json

{
  "name": "Buddy Light",
  "price": 5,
  "description": "Simple Beer"
}

###Update Action for a product
PATCH http://localhost:3000/products/17.json
Content-Type: application/json

{
  "name": "BuddyYay Light",
  "price": 3,
  "description": "Cheap tailgating beer"
}

###Destroy action for one product
DELETE http://localhost:3000/products/5.json


##THESE ARE SUPPLIER ROUTES

###Index Action for all suppliers
GET http://localhost:3000/suppliers

###Show Action for just one supplier
GET http://localhost:3000/suppliers/2

##THESE ARE USER ROUTES

#Create a new user
###
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Joe",
  "email": "joe@aol.com",
  "password": "password"
}

#Login for JWT
###
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "bob@aol.com",
  "password": "password"
}

##THESE ARE ORDER ROUTES

#Create an order
###
POST http://localhost:3000/orders
Authorization: Bearer {{bob}}
Content-Type: application/json

{
  "product_id": 6,
  "quantity": 3
}

#Show action for finding an order
###
GET http://localhost:3000/orders/1
Authorization: Bearer {{bob}}

###Index Action for all orders 
GET http://localhost:3000/orders
Authorization: Bearer {{bob}}

#this is for carted products
###
POST http://localhost:3000/carted_products
Authorization: Bearer {{bob}}
Content-Type: application/json

{
  "product_id": 15,
  "quantity": 2
}

###
GET http://localhost:3000/carted_products